// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGsl72GZ3rTE0Gi1VhQLpGlgyGkr3ipG4',
    appId: '1:576397262267:web:283c43f02d355a505ed89e',
    messagingSenderId: '576397262267',
    projectId: 'dummyriverpod',
    authDomain: 'dummyriverpod.firebaseapp.com',
    storageBucket: 'dummyriverpod.appspot.com',
    measurementId: 'G-EYPE4V3XD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC59D0wDW-ljQ65trPQUia_tEBWnMau5Aw',
    appId: '1:576397262267:android:5b75337db556f9f15ed89e',
    messagingSenderId: '576397262267',
    projectId: 'dummyriverpod',
    storageBucket: 'dummyriverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDiZir3ZBMKCF_ByRO_Ep4tuHiOEZfVow',
    appId: '1:576397262267:ios:cacabdda8737094c5ed89e',
    messagingSenderId: '576397262267',
    projectId: 'dummyriverpod',
    storageBucket: 'dummyriverpod.appspot.com',
    androidClientId: '576397262267-u3tu7hsvvv1kmjagptmmd7ttke6300b0.apps.googleusercontent.com',
    iosClientId: '576397262267-b1s4hl8iqkfe9fugnvevtt68nja8pn9s.apps.googleusercontent.com',
    iosBundleId: 'com.firstlogicmetalab.dummyriverpod.dummyriverpod',
  );
}
